import Head from "next/head";
import { HeaderPage } from "../../components/Header/HeaderPage";
import { TableDatas } from "../../components/TableDatas/TableDatas";
import styles from "./styles.module.scss"

export default function CreditCard() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Seus Cartões</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HeaderPage />
            <button>Adicionar cartão</button>
            <TableDatas titleTable='Cartão Nubank' />
        </div>
    )
}